[theme]
primaryColor = "#DA291C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F5F7"
textColor = "#1E1E1E"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
